name: CI/CD Certify-NFT Backend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Deploy to VPS via Portainer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decode .env files from secrets
        run: |
          echo "${{ secrets.ENV_ROOT_B64 }}" | base64 -d > .env
          echo "${{ secrets.ENV_SERVER_B64 }}" | base64 -d > server/.env

      - name: Remove old folder, container, and image on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gpadaka
            docker rm -f certify-nft-be || true
            docker rmi -f certify-nft-be || true
            rm -rf certify-nft

      - name: Copy project files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/gpadaka/certify-nft"

      - name: Build & Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gpadaka/certify-nft
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d
            docker image prune -f
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: deploy
    if: always()  # jalan meskipun job deploy gagal
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            STATUS="✅ Deployment Succeeded"
            COLOR=3066993
          else
            STATUS="❌ Deployment Failed"
            COLOR=15158332
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "Certify-NFT",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "'"$STATUS"'",
                "description": "Backend deployment to VPS **'"$STATUS"'**",
                "color": '"$COLOR"',
                "fields": [
                  { "name": "Commit", "value": "'"${{ github.event.head_commit.message }}"'" },
                  { "name": "Author", "value": "'"${{ github.actor }}"'" },
                  { "name": "View Commit", "value": "'"$COMMIT_URL"'" }
                ],
                "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
              }]
            }' \
            $DISCORD_WEBHOOK_URL