name: CI/CD Certify-NFT Backend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Deploy to VPS via Portainer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decode .env files from secrets
        run: |
          echo "${{ secrets.ENV_ROOT_B64 }}" | base64 -d > .env
          echo "${{ secrets.ENV_SERVER_B64 }}" | base64 -d > server/.env

      - name: Remove old folder, container, and image on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gpadaka
            docker rm -f certify-nft-be || true
            docker rmi -f certify-nft-be || true
            rm -rf certify-nft

      - name: Copy project files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/gpadaka/certify-nft"

      - name: Build & Compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gpadaka/certify-nft
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d
            docker image prune -f