name: Deploy Certify-NFT Backend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            rm -rf /home/gpadaka/certify-nft
            docker stop certify-nft-be || true
            docker rm certify-nft-be || true
            docker rmi $(docker images -q --filter reference='certify-nft*') || true
          EOF

          scp -r ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/gpadaka/certify-nft

          - name: Decode and Upload .env files
          run: |
            ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
              echo "${{ secrets.ENV_ROOT_B64 }}" | base64 -d > /home/gpadaka/certify-nft/.env
              echo "${{ secrets.ENV_SERVER_B64 }}" | base64 -d > /home/gpadaka/certify-nft/server/.env
            EOFta

      - name: Docker Compose Up
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/gpadaka/certify-nft
            docker compose up -d --build
          EOF