name: Build & Deploy Backend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies & build project
        run: |
          npm install
          npm run build

      - name: Clean old project folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/certify-nft-be

      - name: Copy dist & docker files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,Dockerfile,docker-compose.yml,nginx.conf"
          target: "~/certify-nft-be"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/certify-nft-be
            sudo docker compose down
            sudo docker compose build
            sudo docker compose up -d
            sudo docker image prune -f

      - name: Send Discord notification (Success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
          curl -s -X POST $DISCORD_WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "✅ Deployment Successful",
                "description": "Backend has been successfully deployed to VPS",
                "color": 5763719,
                "fields": [
                  {
                    "name": "Commit",
                    "value": "'$COMMIT_MESSAGE'",
                    "inline": true
                  },
                  {
                    "name": "Author",
                    "value": "'$AUTHOR_NAME'",
                    "inline": true
                  },
                  {
                    "name": "View Commit",
                    "value": "'$COMMIT_URL'",
                    "inline": true
                  }
                ],
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }]
            }'

      - name: Send Discord notification (Failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
          curl -s -X POST $DISCORD_WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "❌ Deployment Failed",
                "description": "Backend deployment to VPS failed",
                "color": 15548997,
                "fields": [
                  {
                    "name": "Commit",
                    "value": "'$COMMIT_MESSAGE'",
                    "inline": true
                  },
                  {
                    "name": "Author",
                    "value": "'$AUTHOR_NAME'",
                    "inline": true
                  },
                  {
                    "name": "View Commit",
                    "value": "'$COMMIT_URL'",
                    "inline": true
                  }
                ],
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }]
            }'
